### ISSUE TITLE
ArMTG Roadmap for 2019

### ISSUE THREAD

**Issue by Qonfused** [CodyJasonBennett/ArMTG#1]
### Phase 1
- [ ] Recognition of up to 60 unique trackers (Corresponding with cards #1-#60)
- [ ] Card image fetching from Decklist (perhaps using the Scryfall API)
### Phase 2
- [ ] GUI for sideboarding (Drag and drop between main/side deck from submitted decklist)
- [ ] Rich Presence integration w/ Discord
### Phase 3
- [ ] GUI for timers (for each round, and for sideboarding)
- [ ] Other game-related info (Cards in hand, library)
### Phase 4
- [ ] GUI for Deckbuilding (stuff like card image preview, similar to that of untap.xyz)
- [ ] GUI for Saving multiple decklists
### Phase 5
- [ ] More advanced metrics like cards in graveyard/exile
- [ ] Interactive Game engine (The stack, and phases)

**Comment by Qonfused** [comment]
### Phase 5+
- [ ] Allowing some handoff between ArMTG and Gatherer for card rulings?
- Perhaps just a link to gatherer, or we could use Scryfall's API for fetching rulings and displaying them.
